name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: npm install --global yarn
      - run: yarn add -D nyc
      - name: Run tests and publish results
        run: |
          yarn test
          ./node_modules/.bin/codecov
        env:
          CODECOV_TOKEN: dc5905ce-46c6-48b8-9ce3-5e7bf4c347da
