name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: npm install --global yarn
      - name: Run tests and publish results
        run: |
          nyc npm test
          nyc report --reporter=lcov
          ./node_modules/.bin/codecov
